#!/bin/bash
DOC=""

DOC+="
 start <uri>
  - start default app that may resolve the requested uri
"
start() {
  shell am start -a android.intent.action.VIEW $@
}

DOC+="
 setDate <date format>
  - change device date using format yyyyMMdd.HHmmss
"
setDate() {
  su date -s $1
}

DOC+="
 getIp
  - Print all IPs for device. Result may vary depend on device.
"
getIp() {
  ip=$(shell netcfg)
  if [[ "$ip"  == *"not found"* ]]; then
    shell ip a
  else
    echo $ip
  fi
}

DOC+="
 getSdk
  - Print device sdk version number
"
getSdk() {
  getprop ro.build.version.sdk
}

DOC+="
 getModel
  - Print device model
"
getModel() {
  getprop ro.product.model
}

DOC+="
 wifiConnect
  - Connectos to a wifi network
"
wifiConnect() {
#  echo "Use one of following:"
#  echo " wifiConnect_service"
#  echo " wifiConnect_file"
#  #wifiConnect_service
  wifiConnect_file
}

DOC+="
 wifiConnect_service <ssid> <password>
  - Connect to wifi network using an android service
  - EXPERIMENTAL
"
wifiConnect_service() {
  shell am startservice \
    -n com.google.wifisetup/.WifiSetupService \
    -a WifiSetupService.Connect \
    -e ssid $1 \
    -e passphrase $2
}

DOC+="
 wifiConnect_file
  - Connect to wifi network using configuration file inside device
  - EXPERIMENTAL - this one works but need futher improvements.
"
wifiConnect_file() {
  echo "Wanted ssid"
  read -e ssid
  echo "Password:"
  read -es pass
  echo "Password manager <WPA-PSK>"
  read -e mgmt
  if [ -z "$mgmt" ]; then
    mgmt="WPA-PSK"
  fi

  { # try
    pull /data/misc/wifi/wpa_supplicant.conf .wifi 
  } || {
    cat >.wifi<<TEXT
ctrl_interface=tiwlan0
update_config=1
device_type=0-00000000-0
TEXT
  }
  cat >>.wifi<<TEXT
network={
  ssid="$ssid"
  psk="$pass"
  key_mgmt=$mgmt
  priority=1
}
TEXT
  push .wifi /data/misc/wifi/wpa_supplicant.conf
  run adb shell chown system.wifi /data/misc/wifi/wpa_supplicant.conf
  run adb shell chmod 660 /data/misc/wifi/wpa_supplicant.conf
  run adb shell am start -a android.intent.action.MAIN -n com.android.settings/.Settings
}

DOC+="
 screenshot [file name]
  - Take a screenshot from device.
"
screenshot() {
  file=screenshot.png
  if [ ! -z "$1" ]; then
    file=$1
  fi
  shell screencap -p /tmp/screencap.png
  pull /tmp/screencap.png $file
  
  orientation=$(orientation)
  echo "Orientation '$orientation'"
  rotation=$(( $orientation * -90 ))
  echo "Rotation '$rotation'"
  run convert $file -rotate $rotation $file
  xdg-open $file &
}

DOC+="
 orientation [direction]
  - Check or Change device orientation device to direction
    none - without parameter, print current orientation
    0 - portrait  - top
    1 - landscape - left
    2 - portrait  - bottom
    3 - landscape - righ
"
orientation() {
  orientation=$1
  if [ -z "$orientation" ];then
    orientation=$(adb shell dumpsys input | grep 'SurfaceOrientation' | grep -oP "\d+" | head -n 1)
    if [ -z "$orientation" ]; then
      # old devices does not have input service, so we need to dump whole sys
      orientation=$(adb shell dumpsys | grep 'SurfaceOrientation' | grep -oP "\d+" | head -n 1)
    fi
    echo $orientation
    exit 0
  fi
  if [[ $orientation -lt 0 || $orientation -gt 4 ]];then
    orientation=0
    echo "Orientation value is invalid"
    return 1
  fi
  echo "Orientation $orientation"
  shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:$orientation
}

DOC+="
 open <home|settings|date>
  - Open a predefined activity
"
open() {
  home() {
    shell am start -a android.intent.action.MAIN -c android.intent.category.HOME
  }
  settings() {
    shell am start -a android.intent.action.MAIN -n com.android.settings/.Settings
  }
  date() {
    shell am start -a android.provider.Settings.ACTION_DATE_SETTINGS
    shell am start -n com.android.settings/.DateTimeSettings
  }
  $1
}

DOC+="
 dev <touch>
  - Manage some dev options
  touch <show|hide>
    - manage touch visibility
      e.g: $0 dev touch show
"
dev() {
  touch() {
    show() {
      shell content insert --uri content://settings/system --bind name:s:show_touches --bind value:i:1
    }
    hide() {
      shell content insert --uri content://settings/system --bind name:s:show_touches --bind value:i:0
    }
    $1
  }
  $@
}

DOC+="
 resolution
  - Print device resolution
"
resolution() {
  shell dumpsys window | grep -A1 Display: | grep -Po "(\d+x\d+)" | head -1
}

DOC+="
 density
  - Print device density
"
density() {
  # grep on the and to remove carriage return (\r)
  getprop ro.sf.lcd_density | grep -Po "(\d+)"
}

DOC+="
 inches
  - Calculate screen inches using resolution and density
"
inches() {
  res=$(resolution)
  res=(${res/x/ })
  density=$(density)
  width=${res[0]}
  height=${res[1]}
  inches=$(bc <<< "scale=3; sqrt( $width^2 + $height^2) / $density ")
  echo $inches
}

# Thanks to MaxChinni https://stackoverflow.com/a/24038245/1622925
DOC+="
 input <record|playback>
  - record and playback inputs on device.
"
input() {
  record() {
    adb shell getevent | grep --line-buffered ^/ | tee /tmp/android-touch-events.log
  }
  playback() {
    awk '{printf "%s %d %d %d\n", substr($1, 1, length($1) -1), strtonum("0x"$2), strtonum("0x"$3), strtonum("0x"$4)}' /tmp/android-touch-events.log | xargs -l echo adb shell sendevent
  }
  $@
}

DOC+="
 install <url>
  - download apk and install on device
"
install() {
  file="/tmp/apk.apk"
  curl -o $file $1
  run adb install $file
}

# Thanks to geffchang https://android.stackexchange.com/a/47994
# and Izzy https://android.stackexchange.com/questions/47989/how-can-i-shutdown-my-android-phone-using-an-adb-command#comment64570_47994
DOC+="
 shutdown
  - shutdown device
"
shutdown() {
  # -p stands for --power-off
  shell reboot -p
}

DOC+="
 su <command>
  - send command as super user
"
su() {
  shell su -c \"$@\" 0
}

# Just a wrapper for adb shell
shell() {
  run adb shell $@
}

# Just a wrapper for adb pull
pull() {
  run adb pull $@
}

# Just a wrapper for adb push
push() {
  run adb push $@
}

DOC+="
 getprop [property name]
  - read a property from device
    If not property were inform print whole property file
"
getprop() {
  if [ -z "$@" ]; then
    shell getprop
  else
    shell getprop $@ | grep -Po "[^\r]+"
  fi
}

# A simple wrapper to print commands in stdout before execute
run() {
  echo \>$@
  $@
}

# Helper command
help() {
  cat <<TEXT
Droid Commands
  General command
$DOC
TEXT
}

if [ "$(type -t $1)" == "function" ]; then
  $@
else
  help
fi
